<html>
<head>
  <?php include 'connection.php' ?>
  <?php
     $email = $_POST['email'];
     $name = $_POST['name'];
     $desig = '2';
     $pass = random_int(1000,9999);
     //$subject = $_POST['subject'];
     //$sql = 'INSERT INTO Table_1 (Name, EmpNo) VALUES (?, ?)';
     $params = array($name,$email,$pass,$desig);

      // // the message
      // $msg = "Greatings ".$name.", you have been registered to CSE Departmental site.\n Please sign up yourself on the site to be able to use thr facilities.\n Your autogenerated password is ".$pass;
      // // use wordwrap() if lines are longer than 70 characters
      // $msg = wordwrap($msg,70);
      // // send email
      // mail("bokaroharsh@gmail.com","My subject",$msg);



     $stmt = sqlsrv_query( $conn,"Insert into emp_details (Name, Email, Password, Designation) VALUES (?,?,?,?);",$params);
     echo '$stmt';
     if($stmt==true)
     {
       echo "true"
       ?>

       <form>
       	<input type="button" id="return_back" value="Return to previous page" onClick="javascript:history.go(-1)" />
       </form>
  <?php
     }
     else{
       ?>
       <h1>
         Error Occoured please try again
        </h1>
       <?php     }
  ?>




  <script type="text/javascript">
  document.getElementById("return_back").click();
  </script>

</head>
<body>
  <h1><?php echo $email ?></h1>
</body>
</html>
